### ISSUE TITLE
Mysql_connect depracted

### ISSUE THREAD

**Issue by Doc1337** [trurascalz/clockworkplugins#7]
ClockWork web databse....

**Comment by trurascalz** [comment]
This is known to me, one temporary work around is using a older version of php(>5.5) I was in the process of changing it to mysqli

**Comment by Doc1337** [comment]
Well I need to use php 7 badly because most things i use depends on it will you change it anytime soon? Also thanks for reply.

**Comment by trurascalz** [comment]
Solved in latest commit.
